### PR TITLE
Changes comment to (maybe) reflect better what it does.

### PR DESCRIPTION
**Pull request by JJ**

### CODE REVIEW

**Comment by ahs502** [comment]
Hi, @JJ !
Glad to see you are interested in this package and contributed to it!
Please, help me understand the issue you tried to fix in this pull request.
As far as I expect from the package, `delete store[...]` is for _synchronous_ operation and `new store(...)` is for _asynchronous_one.

**Comment by JJ** [comment]
I'll have to find out...

**Comment by JJ** [comment]
OK, I've solved the conflict and changed the current description. `new` does not delete, but reset, since it's also creating a new one, right?

**Comment by ahs502** [comment]
Oh, I see!
Well, that actually deletes the file, which will be the same as _resetting_ the file in terms of effects.
However, I agree that the syntax is a bit misleading; for synchronous operations we have the fitting `delete store[...]` option to delete the file, but for asynchronous operation, the nearest option available was the `new` operator, like to `new store(...)` to _renew_ the file.
I understand how you must feel about it and to be honest using `new` for _deleting_ things is not my favorite option either!
For now, please bear with it until I come up with a more intuitive solution.

**Comment by ahs502** [comment]
I'll do a patch for documentation update of this pull request and then publish the package.

**Pull request merged**
